---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-oh-my-zsh
      oh_my_zsh_theme: test_theme1
      oh_my_zsh_custom_themes: tests/themes/*.zsh-theme
      oh_my_zsh_plugins:
        - test_plugin1
        - test_plugin2
      oh_my_zsh_users:
        - username: test_usr1
        - username: test_usr2
          oh_my_zsh:
            theme: test_theme2
            plugins:
              - test_plugin3
              - test_plugin4
            alias:
              - test_alias1
            extra_config:
              - test_line1
      oh_my_zsh_alias:
        - test_alias2
      oh_my_zsh_extra_lines:
        - test_line2
