---
- name: Prepare
  hosts: all

  tasks:
    - name: Create test users
      ansible.builtin.user:
        create_home: true
        home: '/home/{{ item }}'
        name: '{{ item }}'
      loop:
        - test_usr1
        - test_usr2
      become: true

    - name: Install console-setup file
      ansible.builtin.copy:
        dest: /etc/default/console-setup
        force: false
        group: root
        mode: 'u=rwx,go=r'
        owner: root
        src: tests/console-setup.sh
      become: true
